- name: proxmox_cloudinit
  hosts: "{{ template_host }}"
  vars_files:
    - ../vars/proxmox-template.yaml
  gather_facts: true
  serial: 1 # One node at a time
  tasks:
    - include_role:
        name: proxmox-templates